name: cci-source-avail

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cci:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - name: Checkout our repo
      uses: actions/checkout@v3
    - name: Checkout CCI
      uses: actions/checkout@v3
      with:
        repository: conan-io/conan-center-index
        ref: master
        path: cci
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run CCI check script
      run: |
        ./main.py \
          --cci-dir cci \
          --conan-cache-dir cache \
          --source-dir cci-sf \
          --install-dir cci-if
