name: cci-source-avail

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cci:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout our repo
      uses: actions/checkout@v3
    - name: Checkout CCI
      uses: actions/checkout@v3
      with:
        repository: conan-io/conan-center-index
        ref: master
        path: cci
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run CCI check script
      shell: bash
      run: |
        ./main.py \
          --cci-dir cci \
          --conan-cache-dir cache \
          --source-dir cci-sf \
          --install-dir cci-if \
          --filter-recipes
